services:
  - type: web
    name: laravel-todolist
    env: php
    buildCommand: |
      composer install
      cp .env.example .env
      php artisan key:generate
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    plan: free
    region: singapore
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-db-host.render.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: your_database
      - key: DB_USERNAME
        value: your_user
      - key: DB_PASSWORD
        value: your_pass
